# This file was generated by GoReleaser. DO NOT EDIT.
cask "pmm" do
  name "pmm"
  desc "Package Manager Manager v2"
  homepage "https://github.com/ehyland/pmm2"
  version "2.0.0-alpha.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pmm"

  on_macos do
    on_intel do
      url "https://github.com/ehyland/pmm2/releases/download/v#{version}/pmm_Darwin_x86_64.tar.gz"
      sha256 "7d8ab2be95ef2c06d6a7fbe902c6df970644f63b0a3f573daaff44bd09445372"
    end
    on_arm do
      url "https://github.com/ehyland/pmm2/releases/download/v#{version}/pmm_Darwin_arm64.tar.gz"
      sha256 "4b83c441ec64c2ca0014457a936d4b60a9c04f61fc61668683ce39508c9825f1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ehyland/pmm2/releases/download/v#{version}/pmm_Linux_x86_64.tar.gz"
      sha256 "1e47fd14bc8c5d2ac5826ca64aa2b1ea9cddf63b1a70f5d6b546c8e38851afd4"
    end
    on_arm do
      url "https://github.com/ehyland/pmm2/releases/download/v#{version}/pmm_Linux_arm64.tar.gz"
      sha256 "38c4289fa96c4bd8ec2b80838b89c285877ea39e55acacb9022b5c39045c84ea"
    end
  end

  # No zap stanza required
end
