# This file was generated by GoReleaser. DO NOT EDIT.
cask "pmm2" do
  name "pmm2"
  desc "Package Manager Manager v2"
  homepage "https://github.com/ehyland/pmm2"
  version "2.0.0-alpha.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pmm2"

  on_macos do
    on_intel do
      url "https://github.com/ehyland/pmm2/releases/download/v#{version}/pmm2_Darwin_x86_64.tar.gz"
      sha256 "ad03a89ad7b6fdf385af0aeda287129e3b75bbf6f0b1454f54db531dbf9a7aa8"
    end
    on_arm do
      url "https://github.com/ehyland/pmm2/releases/download/v#{version}/pmm2_Darwin_arm64.tar.gz"
      sha256 "01bde61a7ac31b72745e6247bf4f4b63b57141c6726a15638c0baaff8d993390"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ehyland/pmm2/releases/download/v#{version}/pmm2_Linux_x86_64.tar.gz"
      sha256 "cfa620a1e96fe314bb062b398ebfb982bf67500c842d5f64024e009464f9ab91"
    end
    on_arm do
      url "https://github.com/ehyland/pmm2/releases/download/v#{version}/pmm2_Linux_arm64.tar.gz"
      sha256 "9cd245216f9e7b0cba4e79980cdde3a62a397d45838cb790edc2daee9abb773d"
    end
  end

  # No zap stanza required
end
