# This file was generated by GoReleaser. DO NOT EDIT.
cask "pmm2" do
  name "pmm2"
  desc "Package Manager Manager v2"
  homepage "https://github.com/ehyland/pmm2"
  version "2.0.0-alpha.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pmm2"

  on_macos do
    on_intel do
      url "https://github.com/ehyland/pmm2/releases/download/v#{version}/pmm2_Darwin_x86_64.tar.gz"
      sha256 "64de68a8a7751a82f5212722ba3c069e565f63f11d4595954568f6f1e609b65b"
    end
    on_arm do
      url "https://github.com/ehyland/pmm2/releases/download/v#{version}/pmm2_Darwin_arm64.tar.gz"
      sha256 "1f1461b9309a4765c800d80bf6e797bbffad79070c4e7939404e59f09ab6d030"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ehyland/pmm2/releases/download/v#{version}/pmm2_Linux_x86_64.tar.gz"
      sha256 "2885185bec7c596db64458252bd4270fc16255c1892f8eb27c19eccce7e55faa"
    end
    on_arm do
      url "https://github.com/ehyland/pmm2/releases/download/v#{version}/pmm2_Linux_arm64.tar.gz"
      sha256 "393fbc89d60a98001845db5ade14229d0ce46542c49a4af8461110cb7500377e"
    end
  end

  # No zap stanza required
end
